# This is a basic workflow to help get started with Actions

name: Stage the app

# Controls when the workflow will run
on:
  # Triggers the workflow or pull request event
  pull_request:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Conditional that filters "build" job when there is label present called "stage"
    if: contains(github.event.pull_request.labels.*.name, 'stage')
